variables:
  GRADLE_OPTS: 
    -Dorg.gradle.daemon=false
before_script:
  - gradle build
  
  
# Run the following commands
build:
  stage: build
  script:
    - git remote set-url origin https://github.com/BuiltBrokenModding/SBM-BaggableMobs
    - chmod a+x ./gradlew
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
      
deploy:
  stage: deploy
  script:
    - ./gradlew clean build makeChangelog publish curseforge312123 -S -i --refresh-dependencies
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
