# Testfile for gitlabs CI/CD Pipeline and Auto DevOps

# Run seperatly when installing on another device
#  - apt-get install -y sqlite3 libsqlite3-dev nodejs gradle default-jdk
#  - sudo curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
  
variables:
  GRADLE_OPTS: 
    -Dorg.gradle.daemon=false

before_script:
  
  
# Run the following commands
build:
  stage: build
  script:
    - gradle build
    - git remote set-url origin https://github.com/BuiltBrokenModding/SBM-BaggableMobs
    - chmod a+x ./gradlew
    - chmod 770 gradlew
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
    
deploy:
  stage: deploy
  script:
    - ./gradlew clean build makeChangelog publish curseforge312123 -S -i --refresh-dependencies
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

