# Testfile for gitlabs CI/CD Pipeline and Auto DevOps

image: "ruby:2.3.1"

# Uncomment when installing on another device

# before_script:
#  - apt-get install -y sqlite3 libsqlite3-dev nodejs gradle ruby-rspec-core ruby-railties
#  - gem install bundler --no-document
#  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  
# Run the following commands
build:
  script:
    -chmod a+x ./gradlew
    -git remote set-url origin https://github.com/BuiltBrokenModding/SBM-BaggableMobs
    -./gradlew clean build makeChangelog publish curseforge312123 -S -i --refresh-dependencies
