# Testfile for gitlabs CI/CD Pipeline and Auto DevOps

image: gradle:alpine

# Run seperatly when installing on another device
#  - apt-get install -y sqlite3 libsqlite3-dev nodejs gradle
  
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
  

# Run the following commands
build:
  stage: build
  script:
    -gradle --build-cache assemble
    -chmod a+x ./gradlew
    -git remote set-url origin https://github.com/BuiltBrokenModding/SBM-BaggableMobs
    -./gradlew clean build makeChangelog publish curseforge312123 -S -i --refresh-dependencies
  cache:
    key: "$CI_COMMIT_REF_NAME"
#    policy: push
    paths:
      - build
      - .gradle

