# Script for gitlabs CI/CD Pipeline
# Run seperatly when installing on another device
#  - apt-get install -y sqlite3 libsqlite3-dev nodejs gradle default-jdk
#  - sudo curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
  
variables:
  GRADLE_OPTS: 
    -Dorg.gradle.daemon=false
    
#Anything in here will run before each job
before_script:
  
# Builds the mod  
build:
  stage: build
  script:
    - gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/libs
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
    
# Pulls the artifacts(mod jar) from the build job and uploads to curseforge   
deploy:
# Moved from the deploy to the build stage as the deploy stage loves to disappear from the pipeline for no reason.
  stage: build
  script:
    - mkdir libs
    - chmod a+x ./gradlew
    - chmod 770 gradlew
    - git remote set-url origin https://github.com/BuiltBrokenModding/SBM-BaggableMobs
    - ./gradlew clean build makeChangelog publish curseforge312123 -S -i --refresh-dependencies
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/libs
  artifacts:
    paths:
      - /*.html
      - build/libs/*.jar
      - /home/services/dmod/maven/*.jar
    expire_in: 1 week
