# Script for gitlabs CI/CD Pipeline and Auto DevOps

# Run seperatly when installing on another device
#  - apt-get install -y sqlite3 libsqlite3-dev nodejs gradle default-jdk
#  - sudo curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
  
variables:
  GRADLE_OPTS: 
    -Dorg.gradle.daemon=false
    
#Anything in here will run before each stage
before_script:
  - git remote set-url origin https://github.com/BuiltBrokenModding/SBM-BaggableMobs
  
  
# Run the following commands
build:
  stage: build
  script:
    - git remote set-url origin https://github.com/BuiltBrokenModding/SBM-BaggableMobs
    - gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - libs
      - build/libs
      - build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
      
      
make_changelog:
  stage: build
  script:
    - mkdir libs
    - chmod 770 gradlew
    - chmod a+x gradlew
    - git remote set-url origin https://github.com/BuiltBrokenModding/SBM-BaggableMobs
    - ./gradlew makeChangelog
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - libs
      - build/libs
      - build
  artifacts:
    paths:
      - libs/*.html
      - /*.html
    expire_in: 1 week
    
    
deploy:
  stage: deploy
  script:
    - chmod a+x ./gradlew
    - chmod 770 gradlew
    - git remote set-url origin https://github.com/BuiltBrokenModding/SBM-BaggableMobs
    - ./gradlew clean build publish curseforge312123 -S -i --refresh-dependencies
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/libs
      - libs
      - build
      - .gradle
  artifacts:
    paths:
      - libs/*.html
      - /*.html
      - build/libs/*.jar
    expire_in: 1 week

