# Testfile for gitlabs CI/CD Pipeline and Auto DevOps

image: "ruby:2.3.1"

# Run seperatly when installing on another device
#  - apt-get install -y sqlite3 libsqlite3-dev nodejs gradle ruby-rspec-core ruby-railties

before_script:
 - gem install bundler --no-document
 - bundle install --jobs $(nproc)  "${FLAGS[@]}"
 # setup adds gems to Ruby's load path
 - Bundler.setup                    # defaults to all groups
 - require "bundler/setup"          # same as Bundler.setup
 
  
# Run the following commands
build:
  script:
    -chmod a+x ./gradlew
    -git remote set-url origin https://github.com/BuiltBrokenModding/SBM-BaggableMobs
    -./gradlew clean build makeChangelog publish curseforge312123 -S -i --refresh-dependencies
