modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-BaggableMobs/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-baggable-mobs"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="baggablemobs" #mandatory
version="1.0.0" #mandatory
displayName="Baggable Mobs" #mandatory
description='''A simple and configurable mob capture mod''' #mandatory

[[dependencies.baggablemobs]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.baggablemobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"